spring:
  application:
    name: school-service
      
  datasource:
    url: jdbc:postgresql://localhost:5432/SCHOOL_SERVICE
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    
server:
  port: 8000
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka
